'use client'
import './globals.css'
import { Inter } from 'next/font/google'

import { usePathname, useRouter } from "next/navigation";
import { getUserData } from "@/utils/http-service";
import { UserContext } from '@/context/userContext';
import { useState, useEffect } from "react";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const [userData, setUserData] = useState({});
  const pathname = usePathname();
  const router = useRouter();

  useEffect(() => {
    console.log("[userData]: ", userData)
  }, [userData]);

  useEffect(() => {
    getUserData().then((res) => {
      if (res?.status === 200)
        setUserData(res?.data);
      else {
        console.log("[server]: ", res?.data)
        if (pathname === "/login" || pathname === "/signup") return;
        router.push("/login");
      }
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <html lang="en">
      <body className={inter.className}>
        <UserContext.Provider value={{ userData, setUserData }}>
          {children}
        </UserContext.Provider>
      </body>
    </html>
  )
}
