import './globals.css'
import { Inter } from 'next/font/google'
import { StateProvider } from "@/context/userContext"
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Connectify',
  description: 'Generated by sahuyash1103',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <StateProvider>
          {children}
        </StateProvider>
      </body>
    </html>
  )
}
